### PR TITLE
Add "Append item to array" test

### PR DESCRIPTION
**Pull request by sonnyp**

### CODE REVIEW

**Comment by sonnyp** [comment]
https://github.com/sonnyp/json-patch-tests/blob/master/tests.json#L102 ?

nope; my test specifically test pushing a value at the last index + 1

I made the test because all tests would pass except this because my implementation believed it was out of bound

**Comment by mikemccabe** [comment]
https://github.com/sonnyp/json-patch-tests/blob/master/tests.json#L110

**Comment by sonnyp** [comment]
oopsie.

**Comment by sonnyp** [comment]
https://github.com/json-patch/json-patch-tests/pull/21

**Pull request closed without merging**
