### PR TITLE
npm package

### PR DESCRIPTION
**Pull request by sonnyp**
published as https://www.npmjs.com/package/json-patch-test-suite

I'll be happy to hand over npm access

### CODE REVIEW

**Comment by sonnyp** [comment]
ping

**Comment by bruth** [comment]
@mnot Any reservations?

**Comment by mnot** [comment]
Seems reasonable to me.

**Comment by sonnyp** [comment]
what npm username should I add as collaborator?

**Comment by bruth** [comment]
Mine is: bruth

**Comment by sonnyp** [comment]
done

**Pull request merged**
